### ISSUE TITLE
carla control fails to add plugins remotely

### ISSUE THREAD

**Issue by BrainDamage** [falkTX/Carla#1058]
configuration on the host side:
```
cat /tmp/default.carxp
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE CARLA-PROJECT>
<CARLA-PROJECT VERSION='2.0'>
 <EngineSettings>
  <ForceStereo>false</ForceStereo>
  <PreferPluginBridges>true</PreferPluginBridges>
  <PreferUiBridges>true</PreferUiBridges>
  <UIsAlwaysOnTop>false</UIsAlwaysOnTop>
  <MaxParameters>200</MaxParameters>
  <UIBridgesTimeout>4000</UIBridgesTimeout>
 </EngineSettings>

 <Transport>
  <BeatsPerMinute>120</BeatsPerMinute>
 </Transport>
</CARLA-PROJECT>

CARLA_OSC_TCP_PORT=10111 CARLA_OSC_UDP_PORT=10112 carla --no-gui /home/alarm/.config/falkTX/default.carxp 2>&1
Carla 2.0.0 started, status:
  Python version: 3.8.2
  Qt version:     5.14.1
  PyQt version:   5.14.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libjack.so.0 loaded successfully!
Carla ready!
```

on the client, I open carla control, pass the ip address and the ports of the host, also added the ip of the client just to be sure to exclude the auto-detection as potential source of errors

upon client connection, the log writes

 `CarlaEngineOsc::handleMsgRegister() - OSC backend already registered to /ctrl`

and when trying to add a plugin from the client instead it answers

`CarlaEngineOsc::handleMessage() - message not for this client -> '/ctrl/add_plugin' != '/Carla/'`

the same operations, when done locally on the loopback interface work fine

**Comment by falkTX** [comment]
Please try this with latest git/develop version of Carla (or wait some hours, 2.1-RC2 is being prepared)
I believe this is fixed already in there.

**Comment by BrainDamage** [comment]
that specific bug is gone, however, the functionality is still broken, I'll open a new ticket as I'll have more infos
