### ISSUE TITLE
Not Finding VST, DSSI or LADSPA Plugins

### ISSUE THREAD

**Issue by MitchellHa** [falkTX/Carla#1063]
Hello,

I just cloned the latest development branch from GIT for version 2.1-RC1.  Built on Linux with no issues and everything runs.  However, I noticed that available plugins are limited to "Internal" and "LV2" only.  No "LADSPA" or "VST" can be found despite repeated rescans within the Add Plugin dialog.  Paths are all correct to these other plugins and, in fact, I see them pass by in the re-scan dialog, just never actually added and made available.

The same plugins I'm looking to add are available inside my Ardour and Qtractor applications and I can use them there no problem.  Seems strange that Carla cannot pick them up...

Any ideas?

Thanks.

**Comment by falkTX** [comment]
do you get any errors in the logs tab?
this gets reported sometimes, but I was never able to track down why it happens.

**Comment by MitchellHa** [comment]
Thanks for the reply.

So, I started Carla and did another refresh.  The "Run processing checks while scanning" was not checked.  It ran through the scan and I do see the following output in the logs tab;

JUCE v5.2.1


**********************************************************

DexedAudioProcessor Created

Log started: 26 Mar 2020 1:17:15pm


DexedAudioProcessor::DexedAudioProcessor() Hi
int Cartridge::load(const uint8_t*, int) valid sysex found!
void DexedAudioProcessor::setEngineType(int) settings engine 1
void Controllers::refresh() controllers refresh>>> amp_mod 0 pitch_mod 0
virtual void DexedAudioProcessor::setCurrentProgram(int) setting program 0 state
virtual void DexedAudioProcessor::setCurrentProgram(int) setting program 0 state
virtual DexedAudioProcessor::~DexedAudioProcessor() Bye
JUCE Assertion failure in juce_XmlElement.cpp:72
JUCE Assertion failure in juce_XmlElement.cpp:72
...
JUCE Assertion failure in juce_XmlElement.cpp:72

The last JUCE error is probably repeated about 100 or so times in the log.  I did note that it paused on one plugin (Obxd) for a relatively long time, probably the one generating all these log entries.

But, after pausing, it did move on and complete the scan.  But, again, no updates in the plugin library for LADSPA or VST plugins.

**Comment by falkTX** [comment]
Dexed issue is something else, not related to Carla.

Please try a refresh of only LADSPA plugins, and check if that makes any difference.
Thanks.

**Comment by MitchellHa** [comment]
I tried another refresh, just with LADSPA checked.  The refresh ran through much faster and no errors/issues reported in the logs tab.  But, again, nothing added to the plugins collection.

**Comment by falkTX** [comment]
Can you try 2.1-RC2?
I tagged the release and got binaries in the releases section of this github project.

I wonder if there is something weird going on.
So, try removing all carla stuff from ~/.config/falkTX/, and try again too. thanks

**Comment by MitchellHa** [comment]
Unfortunately, no go.  I grabbed latest 2.1-RC2 source, built and ran after removing files in ~/.config/falkTX/, but still same behavior.  Only finds internal and LV2 plugins.  Now, as I mentioned, I did build myself and not run the binaries.  This is because I have QT 5.7 on my system, not 5.9.  Maybe significant, probably not.  Just one difference to note.

**Comment by hijinio** [comment]
Hey there - I believe I have a similar issue, but I'm focused on the Wine bridged VSTs.  I just upgraded to Ubuntu 20.04 from 18.04, where all worked nicely with 2.0.0.  Carla detects the VSTs as shown in the status bar in the "Carla Add New" screen (e.g., 2 VST2 and 2 VST3 plugins), but when I Format filter to VST2, nothing shows up.  I first used the Carla binaries packages, and when that didn't work, I downloaded Carla from the repo using Synaptic.  It's the same outcome on both.  If you can point me to error log, I'd be happy to share.  Or, is there something obvious that I'm missing?  Thanks.

**Comment by falkTX** [comment]
There is a section for the architecture, wine bridges need to be enabled there

**Comment by hijinio** [comment]
Thanks.  Yes, that was already enabled.  I read through this thread carefully again, and took your advice to delete everything in ~/.config/falkTX/.  That did the trick: the VSTs are detected and they appear.  Although, I never had this issue before and there's no clear reason for why it was behaving this way.  Hopefully, this ticket will help others.  BTW, thank you for all your work on this.  Between Steam/Wine/Proton and Carla w/ the Wine bridge, I was able to leave Windows behind last year!

**Comment by gittigger** [comment]
I was just about to post on here that I can reproduce this bug. Then I noticed that the repos have a new version of Carla and so I updated and now I can confirm this is fixed. I think it is likely the root cause of #1118 too. Nice work on getting this fixed up. I thought I was going a little mad till I worked out what wasn't working, then you fixed it up anyway!

**Comment by hijinio** [comment]
Gittigger, glad you chimed in too!  I think it's helpful to know when an issue is isolated to one person or a number of people!

**Comment by gittigger** [comment]
Ahh no worries. Glad to help, indirectly!

**Comment by maddalenina** [comment]
Hello:) I am new to github, I hope I'm not breaking any rule by posting here.
I seem to have the same problem: neither carla nor Ardour are displaying new plugins, even though they are installed in the correct folders (/usr/lib/ladspa and /usr/lib/lv2 for example).
When carla is scanning for new plugins I can see the file names appearing in the progress bar, but after that they are not displayed on the list.
The only plugins that both carla and Ardour are displaying correctly are linux VSTs and pre-existing ones. I have tried clearing the falkTX folder with no luck.. What could I try?
Thank you

**Comment by falkTX** [comment]
did you use carla before?
I think this is an issue from old version of carla messing up with new version data.
so you could try to delete `~/.config/falkTX/` and start carla again

**Comment by maddalenina** [comment]
I only installed carla just yesterday. I have tried deleting the folder and restarting carla several times but it never worked:( It might not be a problem with carla itself since Ardour is not detecting new ladspa/lv2 plugins either

**Comment by falkTX** [comment]
> It might not be a problem with carla itself since Ardour is not detecting new ladspa/lv2 plugins either

that sounds like a system problem indeed.

you can check which lv2 plugins you have installed by running `lv2ls`.
let's try to get LV2 plugins working first, since the scanning for those is automatic.

does `lv2ls` print anything for you?
also, try this and see if any output comes out:
```
/usr/lib/carla/carla-discovery-native lv2 :all
```
thanks

**Comment by maddalenina** [comment]
`lv2ls` returns:
`error: failed to open file /usr/lib/lv2/Dragonfly Reverb/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/Dragonfly%20Reverb/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/Dragonfly%20Reverb/manifest.ttl
http://gareus.org/oss/lv2/gmsynth
http://kxstudio.sf.net/carla/plugins/audiofile
http://kxstudio.sf.net/carla/plugins/audiogain
http://kxstudio.sf.net/carla/plugins/audiogain_s
http://kxstudio.sf.net/carla/plugins/bigmeter
http://kxstudio.sf.net/carla/plugins/carlapatchbay
http://kxstudio.sf.net/carla/plugins/carlapatchbay16
http://kxstudio.sf.net/carla/plugins/carlapatchbay32
http://kxstudio.sf.net/carla/plugins/carlapatchbay3s
http://kxstudio.sf.net/carla/plugins/carlapatchbay64
http://kxstudio.sf.net/carla/plugins/carlapatchbaycv
http://kxstudio.sf.net/carla/plugins/carlarack
http://kxstudio.sf.net/carla/plugins/lfo
http://kxstudio.sf.net/carla/plugins/midichanab
http://kxstudio.sf.net/carla/plugins/midichanfilter
http://kxstudio.sf.net/carla/plugins/midichannelize
http://kxstudio.sf.net/carla/plugins/midifile
http://kxstudio.sf.net/carla/plugins/midigain
http://kxstudio.sf.net/carla/plugins/midijoin
http://kxstudio.sf.net/carla/plugins/midipattern
http://kxstudio.sf.net/carla/plugins/midisplit
http://kxstudio.sf.net/carla/plugins/miditranspose
http://zynaddsubfx.sourceforge.net
http://zynaddsubfx.sourceforge.net/fx#AlienWah
http://zynaddsubfx.sourceforge.net/fx#Chorus
http://zynaddsubfx.sourceforge.net/fx#Distortion
http://zynaddsubfx.sourceforge.net/fx#DynamicFilter
http://zynaddsubfx.sourceforge.net/fx#Echo
http://zynaddsubfx.sourceforge.net/fx#Phaser
http://zynaddsubfx.sourceforge.net/fx#Reverb
https://community.ardour.org/node/7596
urn:ardour:a-comp
urn:ardour:a-comp#stereo
urn:ardour:a-delay
urn:ardour:a-eq
urn:ardour:a-fluidsynth
urn:ardour:a-reverb
`
Whereas `usr/lib/carla/carla-discovery-native lv2 :all` returns 'no such file or directory.

Also, I just checked and new windows vst3s are working just fine with carla.

**Comment by maddalenina** [comment]
`lv2ls` returns:
`error: failed to open file /usr/lib/lv2/Dragonfly Reverb/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file 'file:///usr/lib/lv2/Dragonfly%20Reverb/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/Dragonfly%20Reverb/manifest.ttl
http://gareus.org/oss/lv2/gmsynth
http://kxstudio.sf.net/carla/plugins/audiofile
http://kxstudio.sf.net/carla/plugins/audiogain
http://kxstudio.sf.net/carla/plugins/audiogain_s
http://kxstudio.sf.net/carla/plugins/bigmeter
http://kxstudio.sf.net/carla/plugins/carlapatchbay
http://kxstudio.sf.net/carla/plugins/carlapatchbay16
http://kxstudio.sf.net/carla/plugins/carlapatchbay32
http://kxstudio.sf.net/carla/plugins/carlapatchbay3s
http://kxstudio.sf.net/carla/plugins/carlapatchbay64
http://kxstudio.sf.net/carla/plugins/carlapatchbaycv
http://kxstudio.sf.net/carla/plugins/carlarack
http://kxstudio.sf.net/carla/plugins/lfo
http://kxstudio.sf.net/carla/plugins/midichanab
http://kxstudio.sf.net/carla/plugins/midichanfilter
http://kxstudio.sf.net/carla/plugins/midichannelize
http://kxstudio.sf.net/carla/plugins/midifile
http://kxstudio.sf.net/carla/plugins/midigain
http://kxstudio.sf.net/carla/plugins/midijoin
http://kxstudio.sf.net/carla/plugins/midipattern
http://kxstudio.sf.net/carla/plugins/midisplit
http://kxstudio.sf.net/carla/plugins/miditranspose
http://zynaddsubfx.sourceforge.net
http://zynaddsubfx.sourceforge.net/fx#AlienWah
http://zynaddsubfx.sourceforge.net/fx#Chorus
http://zynaddsubfx.sourceforge.net/fx#Distortion
http://zynaddsubfx.sourceforge.net/fx#DynamicFilter
http://zynaddsubfx.sourceforge.net/fx#Echo
http://zynaddsubfx.sourceforge.net/fx#Phaser
http://zynaddsubfx.sourceforge.net/fx#Reverb
https://community.ardour.org/node/7596
urn:ardour:a-comp
urn:ardour:a-comp#stereo
urn:ardour:a-delay
urn:ardour:a-eq
urn:ardour:a-fluidsynth
urn:ardour:a-reverb
`
Whereas `usr/lib/carla/carla-discovery-native lv2 :all` returns 'no such file or directory'.

Also, I just checked and new windows vst3s are working just fine with carla.

**Comment by falkTX** [comment]
you are missing the first slash in:
```
/usr/lib/carla/carla-discovery-native lv2 :all
```

**Comment by maddalenina** [comment]
haha what a noob. ok, this is the output:
`Error opening file /usr/lib/lv2/Dragonfly Reverb/manifest.ttl (No such file or directory)

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::6

carla-discovery::name::General MIDI Synth

carla-discovery::maker::

carla-discovery::label::gmsynth.lv2/http://gareus.org/oss/lv2/gmsynth

carla-discovery::audio.ins::0

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::Audio File

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/audiofile

carla-discovery::audio.ins::0

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::1

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::Audio Gain (Mono)

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/audiogain

carla-discovery::audio.ins::1

carla-discovery::audio.outs::1

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::1

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::Audio Gain (Stereo)

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/audiogain_s

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::3

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::10

carla-discovery::name::Big Meter

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/bigmeter

carla-discovery::audio.ins::2

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::2

carla-discovery::parameters.outs::2

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::8

carla-discovery::name::Carla-Patchbay

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/carlapatchbay

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::8

carla-discovery::name::Carla-Patchbay (16chan)

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/carlapatchbay16

carla-discovery::audio.ins::16

carla-discovery::audio.outs::16

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::8

carla-discovery::name::Carla-Patchbay (32chan)

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/carlapatchbay32

carla-discovery::audio.ins::32

carla-discovery::audio.outs::32

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::8

carla-discovery::name::Carla-Patchbay (sidechain)

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/carlapatchbay3s

carla-discovery::audio.ins::3

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::8

carla-discovery::name::Carla-Patchbay (64chan)

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/carlapatchbay64

carla-discovery::audio.ins::64

carla-discovery::audio.outs::64

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::8

carla-discovery::name::Carla-Patchbay (CV)

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/carlapatchbaycv

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::5

carla-discovery::cv.outs::5

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::8

carla-discovery::name::Carla-Rack

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/carlarack

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::LFO

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/lfo

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::4

carla-discovery::parameters.outs::1

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI Channel A/B

carla-discovery::maker::Milk Brewster

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midichanab

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::2

carla-discovery::parameters.ins::16

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI Channel Filter

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midichanfilter

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::16

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI Channelize

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midichannelize

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::1

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI File

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midifile

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI Gain

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midigain

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::4

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI Join

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midijoin

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::16

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::10

carla-discovery::name::MIDI Pattern

carla-discovery::maker::falkTX, tatch

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midipattern

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::4

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI Split

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/midisplit

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::16

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::MIDI Transpose

carla-discovery::maker::falkTX

carla-discovery::label::carla.lv2/http://kxstudio.sf.net/carla/plugins/miditranspose

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::1

carla-discovery::parameters.ins::2

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::14

carla-discovery::name::ZynAddSubFX

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynAddSubFX.lv2/http://zynaddsubfx.sourceforge.net

carla-discovery::audio.ins::0

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::16

carla-discovery::parameters.outs::1

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::ZynAlienWah

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynAlienWah.lv2/http://zynaddsubfx.sourceforge.net/fx#AlienWah

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::9

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::ZynChorus

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynChorus.lv2/http://zynaddsubfx.sourceforge.net/fx#Chorus

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::10

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::ZynDistortion

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynDistortion.lv2/http://zynaddsubfx.sourceforge.net/fx#Distortion

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::9

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::ZynDynamicFilter

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynDynamicFilter.lv2/http://zynaddsubfx.sourceforge.net/fx#DynamicFilter

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::8

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::ZynEcho

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynEcho.lv2/http://zynaddsubfx.sourceforge.net/fx#Echo

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::5

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::ZynPhaser

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynPhaser.lv2/http://zynaddsubfx.sourceforge.net/fx#Phaser

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::13

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2

carla-discovery::name::ZynReverb

carla-discovery::maker::ZynAddSubFX Team

carla-discovery::label::ZynReverb.lv2/http://zynaddsubfx.sourceforge.net/fx#Reverb

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::11

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::6

carla-discovery::name::a-Reasonable Synth

carla-discovery::maker::Ardour Team

carla-discovery::label::reasonablesynth.lv2/https://community.ardour.org/node/7596

carla-discovery::audio.ins::0

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::0

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2050

carla-discovery::name::a-Compressor

carla-discovery::maker::Ardour Team

carla-discovery::label::a-comp.lv2/urn:ardour:a-comp

carla-discovery::audio.ins::2

carla-discovery::audio.outs::1

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::8

carla-discovery::parameters.outs::2

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2050

carla-discovery::name::a-Compressor stereo

carla-discovery::maker::Ardour Team

carla-discovery::label::a-comp.lv2/urn:ardour:a-comp#stereo

carla-discovery::audio.ins::3

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::8

carla-discovery::parameters.outs::2

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2050

carla-discovery::name::a-Delay

carla-discovery::maker::Ardour Team

carla-discovery::label::a-delay.lv2/urn:ardour:a-delay

carla-discovery::audio.ins::1

carla-discovery::audio.outs::1

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::9

carla-discovery::parameters.outs::1

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2050

carla-discovery::name::a-EQ

carla-discovery::maker::Ardour Team

carla-discovery::label::a-eq.lv2/urn:ardour:a-eq

carla-discovery::audio.ins::1

carla-discovery::audio.outs::1

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::24

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::6

carla-discovery::name::a-Fluid Synth

carla-discovery::maker::Ardour Team

carla-discovery::label::a-fluidsynth.lv2/urn:ardour:a-fluidsynth

carla-discovery::audio.ins::0

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::12

carla-discovery::parameters.outs::0

carla-discovery::end::------------

carla-discovery::init::-----------

carla-discovery::build::2

carla-discovery::hints::2050

carla-discovery::name::a-Reverb

carla-discovery::maker::Ardour Team

carla-discovery::label::a-reverb.lv2/urn:ardour:a-reverb

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::cv.ins::0

carla-discovery::cv.outs::0

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::3

carla-discovery::parameters.outs::0

carla-discovery::end::------------
`

**Comment by maddalenina** [comment]
haha what a noob. it prints a super long list. anyway, since it seems to be a system problem, i will open a separate issue about it.
thank you very much for your patience, you've been so kind:)

**Comment by falkTX** [comment]
@MitchellHa This is likely now fixed in 2.2-RC1 release, please confirm!
Pre-built binaries at https://github.com/falkTX/Carla/releases/tag/v2.2.0-RC1

**Comment by NotEvenTrying** [comment]
Hello falkTX and others. I'm dealing with a similar issue, but I have some different conditions. Also, I'm kinda noobaf when it comes to Linux and MIDI. A guitarist got it started for me, and I'm still learning. I'm running 20.0.?, I think, and I'm currently using Claudia to launch Carla and saving pre-loaded "studios" for each song's plugins and settings. It works fairly well and switching between studios is quick.  I use an Akai MPKmk3 and a Origin 62 midi controller for inputs and have a Behringer UMC22 for Mic and line level inputs and overall output. It's basically a live-rig. The laptop I'm using, an older Lenovo T410, gets disconnected for other uses, by me, when I'm not practicing. The other day I had it disconnected from the system and dled some vsts from plugins4free so that I could integrate them before the next time I practiced. The next time I plugged everything in most of my plugins were gone and won't "load" when I load up the studio. When I refresh Carla I can see them whiz by in the meter, but they don't populate the list. Do you have any idea why? It's not the first time and I had to rebuild everything last time. Sorry for all the gear talk, but I'm not sure what things are contributing so I figured it could help.

**Comment by NotEvenTrying** [comment]
Sorry, 
OS: Ubuntu 20.04.4 LTS 
Kernel/Version: 5.11.0-17.1-liquorix-amd64
Arch: 64bit

According to Cadence.

**Comment by hijinio** [comment]
Did you have a recent update to Carla? Also, did you try the above and delete the contents of  ~/.config/falkTX/ ? Note: this means you'd have to reconfigure your Carla settings. Try to reboot after you delete and before restarting Carla. (I have a suspicion that there may be a memory leak issue. Someone on Facebook reported this same issue a few days ago, BTW.)

**Comment by NotEvenTrying** [comment]
Thanks Hijinio. Here I will let my noob colors show, lol. As far as I know I haven't had a Carla update recently. Carla was originally installed on my laptop about 18 months ago. I do install weekly Ubuntu updates as they come in, though I don't know if Carla content is included. My guitarist/Linux guru is pretty good about keeping me posted and showing me how to do things. Could you please share the commands and processes that would allow me to delete ~/.carla... I'm nervous because I have a lot of plugins and studios already mapped and it took a while to do. They are saved as CarlaXxxxx files, so I hope it can reinstall them. Sorry I'm noobaf. Thanks again to falkTX for everything, and Hijinio for the prompt reply!

**Comment by hijinio** [comment]
> I'm nervous because I have a lot of plugins and studios already mapped and it took a while to do. 

In that case, you should think long and hard before take any additional steps. Linux has become very easy for anyone to navigate around, but we're talking about is a bit more advanced - especially with you describing that someone else set up your system and you have little experience with Linux. While deleting is easy, the implications are a bit more advanced; i.e., you have to know how to set everything up again. So, deleting that folder will remove your mappings, although your plugins should not be deleted. So, you have two choices: 1) delete and learn how to remap or 2) call your friend for help. :) If you choose #1, you can try something a little less destructive: rename the folder. 

1. Open up a terminal
2. Navigate to the .config folder: type "cd .config"
3. Rename your falkTX folder: type "mv falkTX falkTX-backup"

Then, you can try it out again... maybe even reboot first. (For you lurkers, I know - rebooting is a Windows behavior, but see my note above. There is something weird going on that's triggering this bug. It doesn't hurt to clear the memory to rule out the cause.)

Carla should recreate the .config/falkTX folder. If for some reason, you want to revert, just rename the newest created folder to something else; use step #3 and call it something other than "falkTX-backup". Then, rename your old backup "mv falkTX-backup falkTX".

**Comment by gittigger** [comment]
@NotEvenTrying If you're not confident about going around your Linux install and deleting these kind of hidden folders, I would approach your Linux guru guitarist friend to walk you through this and get them to backup this directory before deleting it. It's been a while since I used this stuff so I can't remember off-hand what might be affected by removing the contents of this folder. Someone else will know, but I just wanted to comment here and say taking a copy of the directory before deletion would probably be prudent. As I recall, my setup was also sensitive to updates from both the Carla side and Ubuntu.

**Comment by robysweettrip** [comment]
I'm having the same issue with a fresh install of 2.4.2 in that VST plugins are not showing up. I tried to follow the tips in here, like deleting the config directory, rebooting, to no avail. Refreshing throws this error in the logs:

```
Traceback (most recent call last):
  File "/usr/share/carla/carla_database.py", line 1692, in slot_refreshPlugins
    if PluginRefreshW(self, self.host, self.fUseSystemIcons, self.hasLoadedLv2Plugins).exec_():
  File "/usr/share/carla/carla_database.py", line 1230, in __init__
    self.fThread.pluginLook.connect(self.slot_handlePluginLook)
TypeError: decorated slot has no signature compatible with SearchPluginsThread.pluginLook[float, str]
```

**Comment by robysweettrip** [comment]
Sounds good, thank for the response.

**Comment by rhalvers** [comment]
I'm seeing this error in Ubuntu 22.04.1 LTS  jammy.  Carla 2.4.2.
Traceback (most recent call last):
  File "/usr/share/carla/carla_database.py", line 1692, in slot_refreshPlugins
    if PluginRefreshW(self, self.host, self.fUseSystemIcons, self.hasLoadedLv2Plugins).exec_():
  File "/usr/share/carla/carla_database.py", line 1230, in __init__
    self.fThread.pluginLook.connect(self.slot_handlePluginLook)
TypeError: decorated slot has no signature compatible with SearchPluginsThread.pluginLook[float, str]

**Comment by falkTX** [comment]
again, 2.4.2 has broken scan, you need 2.4.3 or 2.4.4

**Comment by Tynach** [comment]
> I am in talks with the ubuntu package maintainer to try to bring this update into the repos.

It looks like they tried to build a version of 2.4.2 for Ubuntu Jammy Jellyfish (22.04) with a patch to fix this, but that [the build failed][build].

I know I'm not entitled to this at all, but as I'm using KDE Neon (which is based on LTS releases of Ubuntu), I would greatly appreciate if you could help them get the build working for 22.04.

[build]: https://launchpad.net/ubuntu/+source/carla/2.4.2-0ubuntu3

**Comment by Tynach** [comment]
Actually, you know what? I wanted this because I couldn't get LADSPA working with PipeWire, and figured using Carla would be a 'good enough' workaround.

However, I've found a way to work around Carla's scanning issue, and *then* I found out how to get Pipewire to natively handle LADSPA plugins. I'll now say how I achieved both for the reference of anyone else who stumbles upon this bug report in the future.

## Temporary workaround/fix for Carla

First, to 'fix' Carla temporarily, open up `carla_database.py`. For me on Ubuntu 22.04, this is located at `/usr/share/carla/carla_database.py`. Then comment out line 1230, or whichever line correlates to this function call (near the bottom of the `PluginRefresh(QDialog)` class' `__init__(self, parent)` constructor):

```python
        self.fThread.pluginLook.connect(self.slot_handlePluginLook)
```

After that, start up Carla (if it was already running, make sure to quit the program completely and then start it again) and try to refresh the list of plugins. It should pop up a dialog box with options for what to scan for, instead of doing nothing. This will then allow you to actually perform the scan.

I honestly don't know what all this does, and trying to research that led to a loong chase down a rabbit hole that I eventually gave up finishing. I had tried going down that rabbit hole before even *trying* to just comment it out, so at that time I just wanted something that worked *at all*.

So, because I don't know, I recommend changing the file back (uncommenting the line) after all is said and done. Probably best to completely quit out of Carla first, uncommenting that line, saving the file, and then starting Carla back up again. It should remember all the plugins it scanned (it has in my case, at the very least).

## Get LADSPA and LV2 working in PipeWire

This is a bit off-topic, but ArchWiki — commonly used by non-Arch Linux users — *only* lists [instructions for doing this using Carla][wiki].. Probably because they couldn't get it working either. PipeWire's documentation has a couple of [example configurations][docs] using LADSPA and built-in plugins, but incorrectly claims that

> * `plugin` is the type specific plugin name.
>     * For LADSPA plugins it will append `.so` to find the shared object with that name in the LADSPA plugin path.

And in the provided examples, uses the `plugin` directive as such (**note: *this is wrong***):

> ```
>                  {
>                      type   = ladspa
>                      name   = enc
>                      plugin = surround_encoder_1401 # Specifically, THIS is wrong
>                      label  = surroundEncoder
>                  }
> ```

Other documentation (such as [the changelog for version 0.3.28][changes]) indicates that the PulseAudio module `module-ladspa-sink` is implemented, and while I can't find it now, I've seen somewhere saying that using `pactl` to load that module should work without any changes to its parameters. This is also false.

The fix is thankfully very simple, and was finally [found by Reddit user /u/rustymonster2000][reddit], and then I finally found his post via Google.

Basically, in both PipeWire's config file *and* when using `pactl load-module module-ladspa-sink`, you just have to use the full path to the LADSPA plugin (*including* the `.so` at the end of the filename), instead of just the name of the plugin's file but without the extension (which is all PipeWire's documentation claims is needed). This turns the above example into:

> ```
>                  {
>                      type   = ladspa
>                      name   = enc
>                      plugin = /usr/lib/ladspa/surround_encoder_1401.so # Fixed
>                      label  = surroundEncoder
>                  }
> ```

Given these two workaround/fixes satisfy all the possible needs I can immediately think of, I no longer feel it's necessary for you to waste your time on fixing an old version just for those of us stuck with old versions. I apologize for any of your time I've wasted, and hope that this post can save someone else in the future a lot of hassle.

[wiki]: https://wiki.archlinux.org/title/PipeWire#LADSPA,_LV2_and_VST_plugins
[docs]: https://docs.pipewire.org/page_module_filter_chain.html
[changes]: https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.28
[reddit]: https://old.reddit.com/r/pipewire/comments/yasz39/just_updated_to_ubuntu_2210_and_cant_figure_out/ite1hun/?context=1

**Comment by cleary** [comment]
> > I am in talks with the ubuntu package maintainer to try to bring this update into the repos.
> 
> It looks like they tried to build a version of 2.4.2 for Ubuntu Jammy Jellyfish (22.04) with a patch to fix this, but that [the build failed](https://launchpad.net/ubuntu/+source/carla/2.4.2-0ubuntu3).
> 
> I know I'm not entitled to this at all, but as I'm using KDE Neon (which is based on LTS releases of Ubuntu), I would greatly appreciate if you could help them get the build working for 22.04.

There is a build in the ubuntu backports for 22.04 - you may need to enable the backport repo, but ideally it's already there. Some instructions I posted on the linux musicians forum:

you can verify this with:
```
apt-cache policy carla
carla:
  Installed: 2.4.2-0ubuntu2
  Candidate: 2.4.2-0ubuntu2
  Version table:
     2.5.4-0ubuntu2~bpo22.04.1 100
        100 http://au.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages
 *** 2.4.2-0ubuntu2 500
        500 http://au.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

Which clearly shows the newer version available, but is not a "candidate" for installation - why?

The number (500) next to the universe version is higher than the number next to the backports version (100) - which is a process of prioritisation by apt called "pinning"

You can explicitly specify the version you want to install, but that's a short-term fix only. You want to change the pin priority for carla to get it from the backports repo, and to continue to prioritise that source into the future (in case updates get pushed in)

To change the pin priority, edit a new file: 
```
sudo nano /etc/apt/preferences.d/carla-backports
```

add the following contents:
```
Package: carla*
Pin: release a=jammy-backports
Pin-Priority: 500
```

Then check apt-policy again
```
carla:
  Installed: 2.4.2-0ubuntu2
  Candidate: 2.5.4-0ubuntu2~bpo22.04.1
  Version table:
     2.5.4-0ubuntu2~bpo22.04.1 500
        100 http://au.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages
 *** 2.4.2-0ubuntu2 500
        500 http://au.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

The backport version is now the candidate - you can install all the specific packages you need, or (more easily) do an upgrade:
```
sudo apt-get upgrade
```

and you should see all the newer backport versions coming in (now, and into the future) :D

If the backports are not available, put this into `/etc/apt/sources.list.d/jammy-backports.list`:
```
deb http://au.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
deb-src http://au.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
```
then:
```
sudo apt-get update
```

**Comment by Tynach** [comment]
@cleary, glad to know! I guess that means there are 3 workarounds/fixes available to people on 22.04 :)

**Comment by maxerature** [comment]
Still not working right with 2.5.2 on Pop OS.  Additionally, installing Carla via command line doesn't work for some reason - it doesn't show any audio inputs/outputs.  I need to install via the Pop Shop to get them.

**Comment by falkTX** [comment]
this has long been fixed in 2.5.x series, Ubuntu just does not allow to update these packages so without using any sort of external repo or alternative install, old Ubuntus are stuck with broken Carla version.

**Comment by cleary** [comment]
> this has long been fixed in 2.5.x series, Ubuntu just does not allow to update these packages so without using any sort of external repo or alternative install, old Ubuntus are stuck with broken Carla version.

As per [above](https://github.com/falkTX/Carla/issues/1063#issuecomment-1543056159), ubuntu **do** provide updates via the backports repositories

**Comment by falkTX** [comment]
technically yes... but requires quite the substantial amount of work that realistically almost no one bothers to go through with it or they know people that can help push forward the process.
last time I checked, we needed to:
1. get an official patch fix released by upstream with minimal changes (no updating from 2.3.2 to 2.4.x allowed for example) this is why I created hotfix branches in carla in the first place, and is reasonable
2. have the bugfix pushed into the next release cycle, and have it building correctly (which we had issues with, because of wine related changes that broke the build and needed non-minimal changes to fix), so it can then be backported
3. reason with ubuntu folks on why the update is needed, aka, try to be lucky they consider it a good thing
4. find someone from the right team to test/review the changes and approve them
5. finally get through and push the update

for carla we got stuck at point 2. at least on one of the ubuntu releases, I think a similar case happened in another ubuntu release and I did the hotfix release (so releasing 2.5.x and 2.4.x at the same time) but it was too late as the ones involved with the carla packaging dont have enough time to deal with all this and preparations for the next ubuntu series needed to be prioritized.

I forgot which ubuntu version it is happening in, but one of the issues mentioned on this bug report is fixed by a 1-liner
https://github.com/falkTX/Carla/commit/7e16efba89c180f170c6fe22c773742cfbb89f17
This fix to this day never made it through to the ubuntu repositories

**Comment by cleary** [comment]
I understand there's challenges getting it into the mainline/universe repos, but 2.5.5 is currently sitting in the 22.04 backports repo (it came through in my dist-upgrade the other day):
https://packages.ubuntu.com/jammy-backports/allpackages

To assist with the mainline acceptance, would it help if I log bugs in launchpad, for which you have applied patches? 
That way the Ubuntu packaging team can map some level of requirement to their userbase more easily

**Comment by maxerature** [comment]
So, what?  I'm just SOL?  I don't believe that Pop OS uses the backports.

**Comment by hijinio** [comment]
Sorry, I'm trying to follow the issue here. I'm on Pop!_OS 22.04, although I'm still using 2.4.2 as an LV2 plugin. However, before this, I just installed a newer version by using the KXStudio repo: https://kx.studio/Repositories (which also included dailies, if I remember correctly.) That said, Filipe, I'd still love love love to see the binaries available as a simple download again for Linux, although I realize that it's a pain to compile. ;)

**Comment by Tynach** [comment]
> So, what? I'm just SOL? I don't believe that Pop OS uses the backports.

No @maxerature, read my [earlier comment][wo] where I describe how to work around the issue in the old version of Carla.

[wo]: #issuecomment-1397624260

**Comment by hijinio** [comment]
Hey there - Circling back on this scanning issue which still keeps coming back; [I first chimed in about three years ago](https://github.com/falkTX/Carla/issues/1063#issuecomment-619320506). I didn't realize I was affected by it again because my plugins were scanned/stored by an earlier (working) Carla version before being upgraded along the way.

Carla as a standalone or LV2 refuses to store new wine VST plugins ... even as I can see it scanning them. In fact, the only plugins Carla wants to recognize are the .dlls that Yabridge has created which live in ~/.vst . Stranger yet, I completely delete the ~/.config/falkTX/ folder, reboot, completely remove ALL VST plugin paths within Carla's configuration GUI, and yet, when I run a new scan, it searches ~/.vst , which completely boggles my mind since it should be searching nothing. Logs don't say anything either, and carla_database.py is nonexistent on my system, although /usr/share/carla/ does exist with a bunch of other python files.

Is Carla caching settings somewhere other than ~/.config/falkTX (even temporarily)? It can't be in memory because a reboot would have wiped that. The fact that .vst is being searched without user-defined paths makes me think something else is very wrong. I'm on Pop!_OS 22.04, Carla 2.6.0-alpha1, and Wine 8.12 (staging).

Thanks in advance!

**Comment by falkTX** [comment]
that is a completely different "issue". on latest git versions I am reworking the plugin scanning, still on going and incomplete on some areas particularly:
- plugin folders are hardcoded or fetched via XX_PATH env vars
- only native plugins being scanned
- cache system already in place

the "issue" is unrelated to this ticket, which by now I really want to just close it altogether. the original issue is related to using an old carla version.

anyhow, if you want things to work on a stable predictable way use the stable 2.5.5 release.
when using carla-git expect things to break from time to time, specially now since there is unfinished developments

**Comment by hijinio** [comment]
Thanks, Filipe. The hardcoded part makes sense. Unfortunately, the KXStudio repos for Ubuntu-based systems are mixing 2.5.5 (carla standalone, LV2, VST plugins) with 2.6.0 (all the bridges.) I guess I have to wait it out until 2.6.0 is ready and the repos catch up? What distro do you target? I just may have to try something new altogether.

Yes, you probably should close this thread. I think I saw similar ones for this newer version anyway.

Thanks for the quick response. And thank you very much for making Carla.

**Comment by falkTX** [comment]
the bridges are fine being latest git, and I prefer that to be the case in order to catch any issues early. this mix shouldnt cause any issues, I keep backwards and forwards compat when it comes to bridging in carla

**Comment by hijinio** [comment]
Hmmm... Then I'm not really sure what the issue is then. Even with 2.5.5 and 2.6.0 bridges, the Windows VSTs aren't being picked up. I've tried everything else: this 2.5.5/2.6.0 combination, changing versions of Wine, removing the config directory, rebooting, etc. The logs aren't revealing much either. Short of a full wipe of my OS, I'm not sure what steps to take next to try to correct this issue.

**Comment by falkTX** [comment]
are they enabled on the left side, under architecture?

**Comment by hijinio** [comment]
Yes. I even checked every type of plugin on the view and every type of plugin on scan, just to be sure I didn't miss anything. Experimental is enabled with bridges and wine bridges.

**Comment by falkTX** [comment]
well good thing I am reworking that whole dialog, will make sure that this works proper once I get to implement the wine bridge side

**Comment by hijinio** [comment]
Hi Filipe - Something is definitely broken. I just did a clean install of Ubuntu Studio 22.04. It was still on 2.4.2 with the broken scan. So, I installed the KXStudio repo, updated Carla to 2.5.5 with the 2.6.0 bridges. This is the only change I've made to the install - everything else is out-of-the-box. Same outcome - I can see the VSTs being scanned, but nothing is actually saved and logs show no errors. 

I know you want to close out this thread, but I thought you should be aware considering how critically important Carla is to the audio production community. So, if you prefer that I repost this elsewhere, please let me know. 

Thank you.

**Comment by falkTX** [comment]
I get it, though this is 100% open, patches are welcome and all that.

as last resort drag&dropping a vst2 dll into carla still works.

**Comment by hijinio** [comment]
wow. wow. wow! I never knew you could drag and drop, and I never even considered this. That is an EXCELLENT workaround in the meantime. THANK YOU! (p.s. If was a developer at your level, I'd be happy to look into pitching.)
