### ISSUE TITLE
Plugin 'MidiMultiProgramChange' breaks Carla

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1143]
Simply loading the plugin breaks the Rack tab, I cannot add anything in the rack after, but plugins appear in patchbay.

**Comment by falkTX** [comment]
MidiMultiProgramChange ? what plugin is this?

**Comment by terencode** [comment]
What is shown under the Carla log tab?

**Comment by moonshaadow** [comment]
@falkTX  It's a native vst2 midi plugin by InsertPizHere. I thought you provided it but maybe it comes with ubuntu studio. I don't really need it, I was just testing some plugs
@terencode  unfortunately I am not able to reproduce anymore ( although I had reproduced on  2 different systems)

**Comment by moonshaadow** [comment]
FYI, sources are available [here](https://code.google.com/archive/p/pizmidi/source)

**Comment by terencode** [comment]
Was a bit tedious to get it to compile but I'm able to run it with no issue:

![image](https://user-images.githubusercontent.com/12665563/82741150-835b5700-9d4f-11ea-9340-538fc877104d.png)

If you manage to break it again, don't forget to check the logs.
What carla version are you using?

**Comment by moonshaadow** [comment]
Finally reproduced. Both with 2.2.0-beta1 and 2.1-RC1.
```
Parameter 'CurrentProgram' is NaN! - nan
Parameter 'CurrentProgram' is NaN! - nan
Traceback (most recent call last):
  File "/usr/share/carla/carla_host.py", line 1325, in slot_handlePluginAddedCallback
    pitem = self.ui.listWidget.createItem(pluginId)
  File "/usr/share/carla/widgets/racklistwidget.py", line 241, in createItem
    return RackListItem(self, pluginId)
  File "/usr/share/carla/widgets/racklistwidget.py", line 81, in __init__
    self.recreateWidget(firstInit = True)
  File "/usr/share/carla/widgets/racklistwidget.py", line 171, in recreateWidget
    self.fWidget = createPluginSlot(self.fParent, self.host, self.fPluginId, self.fOptions)
  File "/usr/share/carla/carla_skin.py", line 2064, in createPluginSlot
    return PluginSlot_Presets(parent, host, pluginId, skinColor, skinStyle)
  File "/usr/share/carla/carla_skin.py", line 1827, in __init__
    self.ready()
  File "/usr/share/carla/carla_skin.py", line 638, in ready
    paramWidget.setValue(self.host.get_internal_parameter_value(self.fPluginId, paramIndex))
  File "/usr/share/carla/widgets/pixmapdial.py", line 256, in setValue
    qtValue = round(float(value - self.fMinimum) / float(self.fMaximum - self.fMinimum) * self.fPrecision)
ValueError: cannot convert float NaN to integer
qt.svg: <input>:684: Could not resolve property: pattern5614
qt.svg: <input>:684: Could not resolve property: pattern5626
sorry, can't map this plugin to canvas client 6 6
ERROR: pluginAdded mismatch Id: 7 6
Traceback (most recent call last):
  File "/usr/share/carla/carla_host.py", line 1322, in slot_handlePluginAddedCallback
    pitem.recreateWidget()
AttributeError: 'NoneType' object has no attribute 'recreateWidget'
qt.svg: <input>:684: Could not resolve property: pattern5614
qt.svg: <input>:684: Could not resolve property: pattern5626
```

**Comment by terencode** [comment]
Would you look at that, the same error that I fixed in #1126 :D

Please try to apply it and see if it's fixed.

**Comment by moonshaadow** [comment]
@terencode  Successfully apply your changes and build carla, the bug hasn't appeared. I've tried to load the plugin many times in different contexts, it seems ok! 
Logs still shows :
```
Parameter 'CurrentProgram' is NaN! - nan
Parameter 'CurrentProgram' is NaN! - nan
```

This plugin allows to store and recall presets with different numbers of Program Change for each channel.
Could be useful after all :)

Thank you :+1:

**Comment by terencode** [comment]
@moonshaadow Great! Yeah those are still here because it's still not normal to have NaN as parameters value.

@falkTX Can you merge it?

**Comment by moonshaadow** [comment]
@terencode BTW although the name is good, your screen capture shows MidiProgramChange, which is a different plugin than MidiMultiProgramChange :
![Capture d’écran_2020-05-24_16-53-52](https://user-images.githubusercontent.com/29754932/82757339-20fe6700-9de0-11ea-82d2-4e020e592685.png)

**Comment by terencode** [comment]
Hmm ok weird.

**Comment by moonshaadow** [comment]
In fact no need to build : it comes with kx 
**pizmidi-plugins**  :D
