### ISSUE TITLE
CHOW vst3 UI not displayed properly in plugin version of carla (vst/lv2)

### ISSUE THREAD

**Issue by alex-tee** [falkTX/Carla#1239]
tried with zrythm and ardour, ui is blank:
![Screenshot from 2020-08-17 23-55-42](https://user-images.githubusercontent.com/3407655/90452603-79df5200-e0e6-11ea-9f5b-109676db3b41.png)

same behavior when using the host api

works however in carla standalone (ignore font issue):
![Screenshot from 2020-08-17 23-54-49](https://user-images.githubusercontent.com/3407655/90452636-8f547c00-e0e6-11ea-9735-2c3d02808cdb.png)

**Comment by falkTX** [comment]
Please check again using latest master or develop. This should be fixed now.

**Comment by alex-tee** [comment]
now it works inside the carla lv2 plugin.

I still get the same problem with the host API though

**Comment by falkTX** [comment]
you are calling ui_idle of the native plugin descriptor right? this is a bit tricky situation, since you are trying to show the UI of a plugin, bypassing the native plugin API.

**Comment by alex-tee** [comment]
yeah that's what I'm doing:

```c
self->native_plugin_descriptor->ui_idle (self->native_plugin_handle);
```

on every frame in the GUI thread

**Comment by falkTX** [comment]
confirmed fixed on IRC.

```
19:43 < alextee[m]> falktx: oh it works!
19:43  * alextee[m] uploaded a video: Screencast from 08-09-20 18:43:24.webm (273KiB) < https://matrix.org/_matrix/media/r0/download/matrix.org/vTxsgFGMtKTJmTUhHquMLhnd/Screencast from 08-09-20 18:43:24.webm >
19:44 < alextee[m]> btw, what's up with the fonts in distrho plugins ? falktx:
19:44 < alextee[m]> am i missing a font dependency or something?
19:45 < alextee[m]> surge works
19:45  * alextee[m] uploaded an image: Screenshot from 2020-09-08 18-45-05.png (338KiB) < https://matrix.org/_matrix/media/r0/download/matrix.org/DTpSGtoXLJgGRbjaZskKtFnA/Screenshot from 2020-09-08 18-45-05.png >
```
