### ISSUE TITLE
Patchbay is at times 'wonky' under PipeWire

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1348]
![image](https://user-images.githubusercontent.com/108225/107442521-20089380-6b2f-11eb-9bb7-b4665d351f2e.png)

**Comment by AnotherStateOfMatter** [comment]
I experience the same problem on Manjaro with pipewire 0.3.22.

**Comment by falkTX** [comment]
that is "wonky" for sure.

paging @wtay

**Comment by wtay** [comment]
Last time I checked It was because Carla accessed the objects after the portregistration/registration/connect_callbacks removed the ports, clients and links and the id was already reused for something else. 

To be fair, I think PipeWire can simulate the jack behaviour a bit better (jack keeps separate ids per object type and keeps the objects around for a while longer).

**Comment by falkTX** [comment]
ah might be one of those quirks..

jack api limits what clients can do during these callbacks, so carla handles the ports in a separate event thread of its own.

**Comment by falkTX** [comment]
I wonder if we can fix this in carla by simply not delaying getting info on already-closed/deleted ports. sounds better even for real jack usage anyway.
@mxmilkiib how easy/hard is this to reproduce?

**Comment by wtay** [comment]
It might have improved in master now. There was a problem where a client removed event was emitted wrongly... At least pavucontrol does not leave a mess anymore with master..

**Comment by mxmilkiib** [comment]
I can't try atm, my Arch machine died. Really wasn't hard to reproduce at the time though.

**Comment by AnotherStateOfMatter** [comment]
I just tested Pipewire 0.3.25 with Carla 2.2.0. On earlier versions I had multiple remaining connections to already removed clients within a couple of minutes. On this release of Pipewire and yesterdays session I only saw a single dangling connection over the course of multiple hours and todays session is all good so far. 

So I would say Pipewire 0.3.25 is a big improvement.

@falkTX On earlier versions of Pipewire, the only requirement for reproduction, that I am aware of, was opening and closing several audio clients with Carla running. A few minutes of casual usage usually led to a situation similar to the situation depicted in the original post.

**Comment by ashkitten** [comment]
same for me. 0.3.25 makes these dangling connections significantly less frequent, and refreshing the canvas actually fixes it for me now, which it didn't before.

carla shows this in the log (includes refreshing the canvas, not sure which bit is after refreshing and which is before):
```
Carla assertion failure: "portA != nullptr" in file CarlaEngineJack.cpp, line 4373
Carla assertion failure: "portB != nullptr" in file CarlaEngineJack.cpp, line 4376
Carla assertion failure: "portB != nullptr" in file CarlaEngineJack.cpp, line 4376
PatchCanvas::disconnectPorts(481) - unable to find output port
PatchCanvas::disconnectPorts(553) - unable to find output port
PatchCanvas::disconnectPorts(630) - unable to find output port
PatchCanvas::disconnectPorts(632) - unable to find output port
```

**Comment by falkTX** [comment]
Seems to be fixed for me now with https://github.com/falkTX/Carla/commit/c777cd02d92ba8a61adb29d61fd39f84e3d1bc55
Was easy to reproduce with just firefox starting a webrtc session.
Pipewire was opening, closing and opening a client way too fast.

@wtay the problem was indeed that carla was accessing data after the callback, but the issue is not related to port removal but actually port registration.
By the time carla handled some scheduled jack event, the port that was registered is long gone.

Best would be to make carla more robust against this, so scheduled events cancel if the new port is present on the ports to delete.
But not sure if entirely needed right now, on my system things look to be correct.

Easy to compare new carla:

![Screenshot_20210424_155644](https://user-images.githubusercontent.com/1334853/115962980-af5dfa00-a515-11eb-9c2f-29800ea614bc.png)

With old Catia:

![Screenshot_20210424_155713](https://user-images.githubusercontent.com/1334853/115962991-be44ac80-a515-11eb-9c00-33b01a156ee5.png)

**Comment by falkTX** [comment]
To everyone here, please help by testing!
With pipewire doing jack, alsa and pulse, there is a lot of stuff that can happen, and also go wrong.
I will assume bug is fixed unless anyone says otherwise.

**Comment by sammko** [comment]
There still appear to be some issues. Not sure if this is pipewire related, but it is what I use. Carla version `2.3.0.r3.g491d33f50-1` built on Wed 05 May 2021.
The most common problem is that some links disappear. Ctrl+R sometimes fixes it, sometimes it does not. Occasionally, it is more dramatic:
![image](https://user-images.githubusercontent.com/703905/118340218-5df4c980-b51b-11eb-8b2c-af96407a8f67.png)
There is nothing else being displayed. This instance specifically started out with a dangling edge, so I tried Ctrl+R, after which a bunch of nodes disappeared. Pressing Ctrl+R again ended up in this situation.
Only one message in the logs:

> May 15 01:14:21 --- python3[1874903]: PatchCanvas::CanvasBox.removePort(20) - unable to find port to remove

Restarting Carla is the only way out as far as I know.
I would be glad to help with further debugging.

**Comment by dbogdanov** [comment]
Still an issue with Carla 2.3.0 + pipewire 0.3.40.r59.g1b06d4d-1~ubuntu21.10

**Comment by falkTX** [comment]
2.3 is legacy now, update to 2.4.1

**Comment by lhanson** [comment]
This is using Carla 2.4.1 and latest pipewire commit (15ce86aff):
![carla](https://user-images.githubusercontent.com/273533/146600281-46670183-ce9f-4ddf-b8b0-7de7dcd12631.png)
