### ISSUE TITLE
Bugs with Airwindows and Decent Sampler (linux VST's)

### ISSUE THREAD

**Issue by wujekbrezniew** [falkTX/Carla#1446]
I found some bugs with Carla and plugins in topics so i decided to share them here.

Decent Sampler (linux VST): impossible to load library inside Carla with load button. Tested both in LMMS and Ardour (Carla Patchbay). Loading libraries works fine with standalone version of plugin in Linux.
Log: https://pastebin.com/AAJfNxSM

Airwindows: Saving project inside LMMS with Carla Patchbay and any Airwindows plugin does save Airwindows plugin settings but not shows them after loading in Parameters tab f. e. let's say i set some parameter to 80% and after reload value is loaded but in Parameters tab it is shown as 0%.
Log: https://pastebin.com/9F1xXKiL

Hope this will help with development. :)

**Comment by falkTX** [comment]
The airwindows should be fixed in 2.3.1
Please confirm, with a new project.

**Comment by wujekbrezniew** [comment]
Tested with Carla 2.3.1 embedded in alpha version of LMMS from this [PR](https://github.com/LMMS/lmms/pull/6048). Problem still remains. Maybe this is LMMS side?
