### ISSUE TITLE
XY controller - UI Fails to open and fails to expose outputs as CV output

### ISSUE THREAD

**Issue by JGHFunRun** [falkTX/Carla#1474]
The error I get (in my terminal) when I expose one of the CVs as an output:

```
Carla assertion failure: "paramData.type == PARAMETER_INPUT" in file CarlaPlugin.cpp, line 1789
```

the error I get opening the UI

```
Trying to start UI using "/usr/share/carla/resources/xycontroller-ui"
Traceback (most recent call last):
  File "/usr/share/carla/resources/xycontroller-ui", line 32, in <module>
    import ui_xycontroller
ModuleNotFoundError: No module named 'ui_xycontroller'
waitForClientFirstMessage() - read returned 0
```
I'm on version 2.4.0, downloaded from the KX Studio Repo.

**Comment by falkTX** [comment]
Known issue, has been fixed in carla-git. 2.4.1 to be released in a few weeks.

**Comment by falkTX** [comment]
Wait, the CV one maybe not.
But please check carla-git too for that.

**Comment by jpka-** [comment]
Looks like current git still can't **expose outputs as CV output**, not only for _XY controller_, but for any plugin. Only inputs can. 
Would be happy to be wrong.

**Comment by twonoise** [comment]
See also #1228 .
