### ISSUE TITLE
digitalpeakmeter no longer works

### ISSUE THREAD

**Issue by bingobr** [falkTX/Carla#1548]
Traceback (most recent call last):
  File "/usr/share/carla/widgets/digitalpeakmeter.py", line 427, in paintEvent
    painter.drawLine(2, lsmall - (lsmall * 0.25), lfull-2.0, lsmall - (lsmall * 0.25))
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'int'
  drawLine(self, QLine): argument 1 has unexpected type 'int'
  drawLine(self, int, int, int, int): argument 2 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'int'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'int'

**Comment by falkTX** [comment]
This was fixed in 2.4.1, no?

**Comment by bingobr** [comment]
same issue with carla or carla-git from aur using 2.4.1. 
the meters were working fine earlier, unsure what caused it to break, re-install doesn't solve issue.

**Comment by falkTX** [comment]
converting the code to ensure int type might fix this, like so:
```
painter.drawLine(2, int(lsmall - (lsmall * 0.25)), int(lfull-2), int(lsmall - (lsmall * 0.25)))
```

**Comment by bingobr** [comment]
above fix created more error messages. launching from conda env (python 3.9.7) everything works. launching from system python (3.10.1) meters don't work. no missing dependancies.

**Comment by falkTX** [comment]
Fixed on last git version, release to be made soon
