### ISSUE TITLE
Plugin custom gui crash since a97fd20

### ISSUE THREAD

**Issue by BlueMax** [falkTX/Carla#1731]
Starting with a97fd200fe81e5d64c2db9a3adecac18d17739cf custom GUIs crash when trying to open up. 6ae188765c520a5f986e180ff226b87b99bac9ac is ok. 
Tested with 'x42-eq - Parametric Equalizer Stereo'. Master (378cb66ee599f07908627ff245eae5f8030c4988) is bad as well.

Arch Linux 6.1.7
qt5 5.15.8+kde+r174-1
python-pyqt5 5.15.7
python 3.10.9

**Comment by sfjuocekr** [comment]
Observing a crash when opening Calf plugins, I tested 2.5.0 (working ) and 2.5.3 (not working).

**Comment by falkTX** [comment]
Should be fixed in latest git, I have updated carla-git kxstudio package to match.
Please confirm, I will likely have to do a 2.5.4 bugfix release if it is indeed confirmed.

**Comment by BlueMax** [comment]
Fixed on my side.

Calf plugins work only via 'calfjackhost' for me (for months/years). If i reckon correctly you once said its due to problematic GTK2. Looks like it still works for some people. I'm on XFCE.

**Comment by daveriedstra** [comment]
Seems to work on `2.6.0-alpha1` for me as well, including Calf plugins. ([Panagement](https://www.auburnsounds.com/products/Panagement.html) still crashes though, which is a shame)
