### ISSUE TITLE
gcc 7 warnings about destination buffer overflows, breaking 32bit automated builds for openSUSE

### ISSUE THREAD

**Issue by edogawa23** [falkTX/Carla#495]
I'm maintaining the Carla rpm package, currently at git revision 9ff1711b from Jan 24 2017, for openSUSE. Tumbleweed (the rolling release version of openSUSE) has switched to gcc 7 recently, and it complains with these warnings at compiling source/backend/engine/CarlaEngineBridge.cpp:

[ 300s] g++ ../backend/engine/CarlaEngineBridge.cpp -Wall -Wextra -pipe -DBUILDING_CARLA -DREAL_BUILD -MD -MP -fPIC -DPIC -DNDEBUG -O2 -ffast-math -mtune=generic -msse -msse2 -mfpmath=sse -fdata-sections -ffunction-sections -fvisibility=hidden -DHAVE_DGL -DHAVE_LIBLO -DHAVE_LIBMAGIC -DHAVE_FLUIDSYNTH -DHAVE_LINUXSAMPLER -DHAVE_X11 -DVESTIGE_HEADER -DHAVE_ZYN_DEPS -DHAVE_ZYN_UI_DEPS -std=gnu++0x -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fvisibility-inlines-hidden -fvisibility-inlines-hidden -DBUILD_BRIDGE -I. -I.. -I../backend -I../includes -I../utils -isystem ../modules -I../backend/engine -I../backend/plugin  -DVESTIGE_HEADER    -DIS_CPP11=1 -Wno-non-virtual-dtor -Wno-shadow -Wno-unused-parameter -c -o ../../build/bridges-plugin/Release/CarlaEngineBridge.cpp.o
[  301s] In file included from /usr/include/string.h:639:0,
[  301s]                  from /usr/include/c++/7/cstring:42,
[  301s]                  from ../utils/CarlaUtils.hpp:27,
[  301s]                  from ../utils/CarlaOscUtils.hpp:21,
[  301s]                  from ../backend/engine/CarlaEngineOsc.hpp:26,
[  301s]                  from ../backend/engine/CarlaEngineInternal.hpp:21,
[  301s]                  from ../backend/engine/CarlaEngineBridge.cpp:22:
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  301s] In function 'void* memcpy(void*, const void*, size_t)',
[  301s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  301s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  301s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  301s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  301s]                                                                        ^
[  302s] In function 'void* memcpy(void*, const void*, size_t)',
[  302s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  302s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:169:23:
[  302s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  302s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  302s]                                                                        ^
[  302s] In function 'void* memcpy(void*, const void*, size_t)',
[  302s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  302s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  302s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  302s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  302s]                                                                        ^
[  302s] In function 'void* memcpy(void*, const void*, size_t)',
[  302s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  302s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:169:23:
[  302s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  302s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  302s]                                                                        ^
[  302s] In function 'void* memcpy(void*, const void*, size_t)',
[  302s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  302s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  302s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  302s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  302s]                                                                        ^
[  302s] In function 'void* memcpy(void*, const void*, size_t)',
[  302s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:356:24,
[  302s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:175:23:
[  302s] /usr/include/bits/string3.h:53:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  302s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  302s]                                                                        ^

The compilation continues, but at the end there are some post-install checks that decide that these are too severe to let the rpm be published.

I've tried to understand the code but it's over my head. fundamental in freenode #lad gave me a hint to try removing the const in source/utils/CarlaRingBuffer.hpp line 334 which reads:
`        uint8_t* const bytebuf(static_cast<uint8_t*>(buf));`
or explicitely cast to void* in the two memcpy() calls at line 356 and 357. I tried both without success and am clueless now, my C++ skills are obviously rudimentary...

**Comment by falkTX** [comment]
I believe this should be fixed in latest master, please recheck

**Comment by edogawa23** [comment]
Unfortunately this does not fix the issue,here follow the corresponding warnings from current x86 buildlog:
[  443s] g++ ../backend/engine/CarlaEngineBridge.cpp -Wall -Wextra -pipe -DBUILDING_CARLA -DREAL_BUILD -MD -MP -fPIC -DPIC -DNDEBUG -O2 -ffast-math -mtune=generic -msse -msse2 -mfpmath=sse -fdata-sections -ffunction-sections -fvisibility=hidden -DHAVE_PYQT -DHAVE_FLUIDSYNTH -DHAVE_HYLIA -DHAVE_LIBLO -DHAVE_LIBMAGIC -DHAVE_LINUXSAMPLER -DHAVE_X11   -DCARLA_LIB_EXT=\".so\" -DHAVE_EXTERNAL_PLUGINS -DHAVE_DGL -DHAVE_ZYN_DEPS -DHAVE_ZYN_UI_DEPS -std=gnu++0x -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fvisibility-inlines-hidden -fvisibility-inlines-hidden -DBUILD_BRIDGE -I. -I.. -I../backend -I../includes -I../utils -isystem ../modules -I../backend/engine -I../backend/plugin     -DIS_CPP11=1 -Wno-non-virtual-dtor -Wno-shadow -Wno-unused-parameter   -c -o ../../build/bridges-plugin/Release/CarlaEngineBridge.cpp.o
[  445s] In file included from /usr/include/string.h:494:0,
[  445s]                  from /usr/include/c++/7/cstring:42,
[  445s]                  from ../utils/CarlaUtils.hpp:27,
[  445s]                  from ../utils/CarlaOscUtils.hpp:21,
[  445s]                  from ../backend/engine/CarlaEngineOsc.hpp:26,
[  445s]                  from ../backend/engine/CarlaEngineInternal.hpp:21,
[  445s]                  from ../backend/engine/CarlaEngineBridge.cpp:22:
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:166:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = SmallStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'virtual void CarlaBackend::CarlaEngineBridge::run()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 4098 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  445s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  445s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:166:23:
[  445s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  445s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  445s]                                                                        ^
[  445s] In function 'void* memcpy(void*, const void*, size_t)',
[  446s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  446s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  446s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  446s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  446s]                                                                        ^
[  446s] In function 'void* memcpy(void*, const void*, size_t)',
[  446s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  446s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:166:23:
[  446s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  446s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  446s]                                                                        ^
[  446s] In function 'void* memcpy(void*, const void*, size_t)',
[  446s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  446s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  446s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  446s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  446s]                                                                        ^
[  446s] In function 'void* memcpy(void*, const void*, size_t)',
[  446s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  446s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  446s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  446s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  446s]                                                                        ^
[  446s] In function 'void* memcpy(void*, const void*, size_t)',
[  446s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  446s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  446s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  446s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  446s]                                                                        ^
[  446s] In function 'void* memcpy(void*, const void*, size_t)',
[  446s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  446s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  446s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  446s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  446s]                                                                        ^
[  446s] In function 'void* memcpy(void*, const void*, size_t)',
[  446s]     inlined from 'bool CarlaRingBufferControl<BufferStruct>::tryRead(void*, uint32_t) [with BufferStruct = BigStackBuffer]' at ../utils/CarlaRingBuffer.hpp:353:24,
[  446s]     inlined from 'void CarlaBackend::CarlaEngineBridge::handleNonRtData()' at ../utils/CarlaRingBuffer.hpp:172:23:
[  446s] /usr/include/bits/string_fortified.h:34:71: warning: 'void* __builtin___memcpy_chk(void*, const void*, unsigned int, unsigned int)': writing between 16386 and 4294967295 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
[  446s]    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
[  446s]                                                                        ^

**Comment by falkTX** [comment]
I still can't reproduce this, even with gcc7 and the same flags as you.
Those flags introduced there seem a little overkill, makes me think they will degrade the performance of carla's backend.
Are you allowed to skip those flags?
ie, can you do `make CFLAGS="" CXXFLAGS=""` and still have the package accepted?

**Comment by edogawa23** [comment]
I can skip these flags when building carla in my home project, of course. But I'm not sure if that would get accepted for the distro version. 
Anyway I tend to think to just leave this all as-is and stop supporting 32bit altogether, openSUSE stable releases after all are published only for x64_86 since some time, I myself don't run any x86 systems anymore, we don't build for 32bit since this issue appeared almost a year ago and I never got complaints from anyone so far...

**Comment by falkTX** [comment]
Okay, if it's not a real problem then feel free to close it.
