### ISSUE TITLE
Canvas keyboard is grayed out: no clues how to use it

### ISSUE THREAD

**Issue by midenok** [falkTX/Carla#883]
It's quite puzzling of how to use it since it's not activated when some instruments exist on rack that do work from their own keyboards. Others also faced same issue:

https://linuxmusicians.com/viewtopic.php?f=47&t=19684

Btw, I would love to know the secret too!

**Comment by trebmuh** [comment]
Screenshot please ?

**Comment by midenok** [comment]
Screenshot of grayed out keyboard? NP.

![image](https://user-images.githubusercontent.com/3307037/57212421-532e0280-6fec-11e9-9784-d27eb31698d7.png)

**Comment by trebmuh** [comment]
Maybe you need to:
1) select the "Carla" box in order to activate the keyboard
2) connect the "Carla" box to the system outputs (System playback_1 & playback_2)

**Comment by midenok** [comment]
@trebmuh Is this a real solution or just guessing?

**Comment by falkTX** [comment]
the canvas keyboard will send events to the currently selected plugin.
this is mostly useful just in patchbay and multi-client modes.

in the develop branch, selecting carla under rack mode will send midi notes to the first plugin in the rack

**Comment by BlueMax** [comment]
Is it supposed to work in 'Multiple Clients' process mode? I have the plugin selected but the keyboard is still gray.

Arch Linux
carla-git 1:2.1.alpha2.r156.ga1f759bc-1

![carla-keyboard](https://user-images.githubusercontent.com/1403092/61559317-b4049d00-aa69-11e9-9be7-da5ee364cc8c.png)

**Comment by trebmuh** [comment]
Yes. It works here (Carla 2.0.0) :

![carla-synthv1](https://user-images.githubusercontent.com/8705846/62541424-090e2480-b85a-11e9-974b-760c8760d377.png)

**Comment by falkTX** [comment]
I think this is an issue only on the linux binary builds.
Will release a fix somewhat soon

**Comment by BlueMax** [comment]
Looks like its fixed now on Linux/master. The keyboard properly lights up here on every plugin with 'events-in'. Can anyone confirm?

**Comment by SPOOKY1369** [comment]
If this matter is not solved yet load any plugin that uses a keyboard. like yoshimi, and click on the wrench icon. This brings up the keyboard and it is fully functional. When played with keyboard keys, the keys don't light up, they only light with a mouse click, but it is a full keyboard and functional.

**Comment by federicobriata** [comment]
yes I've too the same issue now after upgrade to carla-git 5:2.1+git20200422.3

**Comment by federicobriata** [comment]
@falkTX could be a regression?

**Comment by BlueMax** [comment]
Does work properly here. Tested with yoshimi.

Arch Linux
carla-git 1:2.1.r43.gc1c406c7f-1 (2020.05.07)

**Comment by GMP69** [comment]
I've been having this same problem the past couple of months. When I first tried Carla earlier this year, the keyboard worked fine. If I click the wrench in the Rack, that keyboard works fine. It's just the patchbay one (which is much more useful!). I'm on Ubuntu Studio 18.04 with KX repositories.
![Screenshot_2020-07-07_13-01-24](https://user-images.githubusercontent.com/67958981/86778496-57bbd400-c052-11ea-8fda-08c2a2db50d6.jpg)

**Comment by falkTX** [comment]
That is expected, and will get "worse" with carla 2.2 coming in a few weeks.
Basically, you need update your JACK version to one that provides meta-data support, that is 1.9.13 or above.

On Ubuntu 18.04 you can simply use https://kx.studio/Repositories:Extras

**Comment by falkTX** [comment]
And since the issue with the binary builds has been fixed in 2.1, I am closing this issue.

I still need to make a repo for 20.04 like the one above (in extras), but that is a separate issue.

**Comment by GMP69** [comment]
Thanks very much for the info, much appreciated :)

**Comment by federicobriata** [comment]
@falkTX I'm using ppa bionic, from the moment I've upgraded to 2.1+git20200422.3 the keyboard is grayed out (previous 2.1 was working properly), today I tried upgrade to latest 2.2~beta1+git20200701 and the issue iis still the same. 
So maybe we have another issue related still to this.

**Comment by falkTX** [comment]
maybe jack2 got updated/downgraded while carla-git was updated at the same time?

**Comment by federicobriata** [comment]
@falkTX my jack2 is 1.9.12-dfsg-2 (from debian stable), do I need to add ppa extra you suggested?

**Comment by falkTX** [comment]
That PPA is only for Ubuntu 18.04, and won't work anywhere else.
(contrary to the kxstudio repositories which, although based on bionic, have all packages statically built so they work everywhere)

Carla from 2.1 onwards requires a JACK version that supports meta-data, I had to go this way otherwise some nasty race conditions would happen, which usually would result in crashes.
Carla 2.2 will make even more use of JACK meta-data, as the client positions in the canvas are now managed by meta-data.

So your choices are:
1. Find a way to get JACK 1.9.14 or later into your distribution
2. Revert to using Carla 2.0 (and be ok with the lack of support for it)
3. Switch engine mode to Patchbay instead of multi-client, but then Carla will have a separated internal + external patchbay (the internal one for carla and its plugins, and the JACK one)
4. Use JACK1 instead of JACK2, which I believe has meta-data support in Debian packages
