### ISSUE TITLE
Plugin right-click menu items disappear after a rename

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#994]
After renaming VCO3, all right-click menu items under Split disappear.

**Comment by mxmilkb** [comment]
Also, I think Carla starts to get confused about what graph node is what - right clicking and Rename on some gives another nodes name, and changing/saving that changes the other node, not the intended one.

**Comment by falkTX** [comment]
Fixed in 7d907da527967f1d3fdcaa350ea3105b0ef32994

**Comment by mxmilkb** [comment]
I'm still getting the same issue after a while when adding and removing plugins.

(I think I mentioned this before on IRC, but I'm mentioning it here again in case there were crossed wires at that point. Or, is it as you mentioned in #jack, a JACK internal client issue, not a Carla one?)

**Comment by falkTX** [comment]
Are you running more than 1 carla instance?

**Comment by mxmilkb** [comment]
Nope.

**Comment by falkTX** [comment]
and you are sure you have running carla from git?
I verified the fix myself..
